stages:
  - test
  - build

include:
  - template: Security/SAST.gitlab-ci.yml

image: node:lts

variables:
  NEXT_TELEMETRY_DISABLED: 1
pages:
  stage: build
  script:
    - yarn
    - yarn build
    - yarn export
    - rm -rf public/*
    - mv out/* public
  artifacts:
    paths:
      - public
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - node_modules/
    - .next/cache/
  only:
    - release
