include:
  - template: Security/SAST.gitlab-ci.yml

image: node:lts

cache:
  paths:
    - node_modules/

pages:
  before_script:
    # Clean 'public' directory
    - find public -mindepth 1 -maxdepth 1 -type d | xargs rm -rf
    - find public -type f -name "*.html" | xargs rm -rf
    # Install packages
    - yarn install
  script:
    - yarn publish
    - mv out/* public
  artifacts:
    paths:
      - public
  only:
    - release
